stages:
  - build
  - test
  - review

variables:
  DANGER_GITLAB_API_TOKEN: "yNhUGSrfa6f-D_w2kTTp"
  DANGER_GITLAB_HOST: "git.douglastaquary.com"
  DANGER_GITLAB_API_BASE_URL: "https://gitlab.com/api/v4"

before_script:
  - export PULL_REQUEST_ID=$(git ls-remote -q origin merge-requests\*\head | grep $CI_COMMIT_SHA | sed 's/.*refs\/merge-requests\/\([0-9]*\)\/head/\1/g')
  - export PR_BRANCH=$(curl -s "https://git.example.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?private_token=${OAUTH_TOKEN}&state=opened" | jq -r ".[]|select(.sha == \"$CI_COMMIT_SHA\")|.source_branch")
  - export PR_ID=$(curl -s "https://git.example.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?private_token=${OAUTH_TOKEN}&state=opened" | jq -r ".[]|select(.sha == \"$CI_COMMIT_SHA\")|.iid")
  - export CI_MERGE_REQUEST_ID=$(curl -s "https://git.example.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?private_token=${OAUTH_TOKEN}&state=opened" | jq -r ".[]|select(.sha == \"$CI_COMMIT_SHA\")|.iid")

test-sim:
  stage: test
  script:
    #- pod install
    - xcodebuild clean -workspace BuckDemoApp.xcworkspace -scheme BuckDemoApp
    - xcodebuild test -workspace BuckDemoApp.xcworkspace -scheme BuckDemoApp -destination 'platform=iOS Simulator,name=iPhone X,OS=11' 
  tags:
    - ios_11
    - xcode_10-2
    - osx_10-15

build_project:
  stage: build
  script:
    - xcodebuild clean -project BuckDemoApp.xcodeproj -scheme BuckDemoApp | xcpretty
    - xcodebuild test -project BuckDemoApp.xcodeproj -scheme BuckDemoApp -destination 'platform=iOS Simulator,name=iPhone X,OS=11' | xcpretty -s
  tags:
    - ios_11
    - xcode_10-2
    - osx_10-15
danger:
  stage: review
  script:
   # - bundle install
    - bundle exec danger --verbose
  tags:
    - ios_11
    - xcode_10-2
    - osx_10-15