load("//Config:configs.bzl", "app_binary_configs", "library_configs", "pretty", "info_plist_substitutions", "bundle_identifier", "DEVELOPMENT_LANGUAGE")

apple_asset_catalog(
    name = "BuckDemoAppAssets",
    visibility = ["//BuckDemoApp:"],
    app_icon = "AppIcon",
    dirs = ["Assets.xcassets"],
)

xcode_workspace_config(
    name = "workspace",
    workspace_name = "BuckDemoApp",
    src_target = ":BuckDemoApp",
    action_config_names = {"profile": "Profile"},
)

# apple_library(
#     name = "BuckDemoLibrary",
#     visibility = [
#         "//BuckDemoApp:",
#         "//BuckDemoApp/...",
#     ],
#     configs = library_configs(),
#     swift_version = "5",
#     srcs = [
#         "ViewController.swift",
#         "AppDelegate.swift",
#     ],
#     #tests = app_tests,
#     deps = [

#         ":BuckDemoAppAssets",

#         # Resources
#         "//BuckDemoApp:StoryboardResources",
#     ],

# )

apple_binary(
    name = "BuckDemoAppBinary",
    visibility = [
        "//BuckDemoApp:",
        "//BuckDemoApp/...",
    ],
    configs = app_binary_configs("BuckDemoApp"),
    preprocessor_flags = ['-fobjc-arc', '-Wno-objc-designated-initializers'],
    swift_version = "5",
      srcs = glob([
        "ViewController.swift",
        "AppDelegate.swift",
    ]),
    frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
  ],
    deps = [
        
        ":BuckDemoAppAssets",

        # Resources
        "//BuckDemoApp:StoryboardResources",
    ],
)

apple_resource(
    name = "StoryboardResources",
    visibility = ["//BuckDemoApp:"],
    variants = glob([
        "*.lproj/*.storyboard",
    ]),
)

apple_bundle(
    name = "BuckDemoApp",
    visibility = [
        "//BuckDemoApp:",
    ],
    extension = "app",
    binary = ":BuckDemoAppBinary",
    product_name = "BuckDemoApp",
    info_plist = "Info.plist",
    info_plist_substitutions = info_plist_substitutions("BuckDemoApp"),
)


apple_package(
    name = "BuckDemoAppPackage",
    bundle = ":BuckDemoApp",
)